export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATEGORIES_START: 'FETCH-CATEGORIES-START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH-CATEGORIES-SUCCESS',
    FETCH_CATEGORIES_ERROR: 'FETCH-CATEGORIES-ERROR',
}